tap "homebrew/bundle"
tap "koekeishiya/formulae"
tap "zegervdv/zathura"
brew "glib"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "adwaita-icon-theme"
brew "dbus"
brew "bat"
brew "black"
brew "unbound"
brew "gnutls"
brew "emacs"
brew "cask"
brew "clang-format"
brew "cowsay"
brew "eza"
brew "fd"
brew "fortune"
brew "fzf"
brew "little-cms2"
brew "ghostscript"
brew "gsettings-desktop-schemas"
brew "python@3.12"
brew "gtk+3"
brew "hydra"
brew "icu4c@75"
brew "mas"
brew "meson"
brew "minimal-racket"
brew "mysql-client"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "node"
brew "pipx"
brew "poppler"
brew "pyright"
brew "rclone"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "tree"
brew "typst"
brew "unison"
brew "z"
brew "koekeishiya/formulae/yabai"
brew "zegervdv/zathura/zathura"
brew "zegervdv/zathura/zathura-pdf-poppler"
cask "brave-browser"
cask "firefox"
cask "font-hack-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "mactex"
cask "nordvpn"
cask "notion"
cask "obsidian"
cask "ollama-app"
cask "r-app"
cask "rstudio"
cask "skim"
cask "utm"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "CrystalFetch", id: 6454431289
mas "GarageBand", id: 682658836
mas "Goodnotes", id: 1444383602
mas "HP Smart", id: 1474276998
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
vscode "asvetliakov.vscode-neovim"
vscode "dracula-theme.theme-dracula"
vscode "james-yu.latex-workshop"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-explorer"
vscode "twxs.cmake"
